repos:
  - repo: local
    hooks:
      - id: validate-tool-versions
        name: Validate tool versions
        entry: ./tools/pre-commit/check-tool-versions.sh
        language: script
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
        name: Don't commit to main branch
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-symlinks
        name: Check for broken symlinks
      - id: check-json
        name: Check for valid JSON
      - id: check-yaml
        exclude: (tools/environments/test_config/invalid.yaml)
        name: Check for valid YAML
      - id: detect-private-key
        name: Check for private keys
      - id: trailing-whitespace
        name: Fix trailing whitespaces
      - id: end-of-file-fixer
        name: Fix missing end-of-file line returns
        exclude: repository.yaml
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_fmt
        name: Run Terraform Formatter
  - repo: https://github.com/pecigonzalo/pre-commit-terraform-vars
    rev: v1.0.0
    hooks:
      - id: terraform-vars
        name: Check for unused Terraform variables
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: terragrunt-hclfmt
        name: Run Terragrunt Formatter
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        name: Re-order Python imports
        entry: env SETUPTOOLS_USE_DISTUTILS=stdlib reorder-python-imports
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Run Black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Run Bandit
        args: [-ll, -s, B605]
        language_version: python3
