[tool.poetry]
name = "{{package_name}}"
version = "0.0.0"
description = "Python wrapper for terragrunt"
readme = "README.md"
authors = ["Lee Myring <29373851+thinkstack@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
#pyyaml = "*"
#python-terraform = "^0.10.1"
pyyaml = "^6.0"
python-terraform = "^0.10.1"

[tool.poetry.dev-dependencies]
#bandit = "*"
#pytest = "^6.1.2"
#pytest-cov = "^2.10.1"
#pytest-pycodestyle = "^2.2.0"
#reorder-python-imports = "^2.3.6"
#black = "^20.8b1"
#pytest-black = "^0.3.12"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
